StockMarket/StockMarket/Models/Stock.cs
namespace StockMarket.Models;

public class Stock
{
    public string? StockSymbol { get; set; }
    public string? StockName { get; set;}

    public override bool Equals(object? obj)
    {
        if (obj == null) return false;
        if (obj is not Stock) return false;

        Stock other = (Stock)obj;
        return StockSymbol == other.StockSymbol && StockName == other.StockName;
    }
}

StockMarket/StockMarket/Controllers/StocksController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using ServiceContracks;
using StockMarket.Models;

namespace StockMarket.Controllers
{
    [Route("[controller]")]
    public class StocksController : Controller
    {
        private readonly TradingOptions _tradingOptions;
        private readonly IFinnhubService _finnhubService;
        private readonly ILogger<StocksController> _logger;

        /// <summary>
        /// Constructor for TradeController that executes when a new object is created for the class
        /// </summary>
        /// <param name="tradingOptions">Injecting TradeOptions config through Options pattern</param>
        /// <param name="finnhubService">Injecting FinnhubService</param>
        /// <param name="logger">Injecting ILogger<StocksController></param>
        public StocksController(IOptions<TradingOptions> tradingOptions, IFinnhubService finnhubService, ILogger<StocksController> logger)
        {
            _tradingOptions = tradingOptions.Value;
            _finnhubService = finnhubService;
            _logger = logger;
        }

        [Route("/")]
        [Route("[action]/{stock?}")]
        [Route("~/[action]/{stock?}")]
        public async Task<IActionResult> Explore(string? stock, bool showAll = false)
        {
            // Logger
            _logger.LogInformation("In StocksController.Explore() action method");
            _logger.LogDebug("stock: {stock}, showAll: {showAll}", stock, showAll);

            //get company profile from API server
            List<Dictionary<string, string>>? stocksDictionary = await _finnhubService.GetStocks();

            List<Stock> stocks = new List<Stock>();

            if (stocksDictionary is not null)
            {
                if(!showAll && _tradingOptions.Top25PopularStocks != null)
                {
                    string[]? Top25PopularStocksList = _tradingOptions.Top25PopularStocks?.Split(",");
                    if (Top25PopularStocksList is not null)
                    {
                        stocksDictionary = stocksDictionary
                         .Where(temp => Top25PopularStocksList.Contains(Convert.ToString(temp["symbol"])))
                         .ToList();
                    }

                    //convert dictionary objects into Stock objects
                    stocks = stocksDictionary
                     .Select(temp => new Stock() { StockName = Convert.ToString(temp["description"]), StockSymbol = Convert.ToString(temp["symbol"]) })
                    .ToList();
                }
            }

            ViewBag.stock = stock;
            return View(stocks);
        }
    }
}

StockMarket/StockMarket/ViewComponents/SelectedStockViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using ServiceContracks;

namespace StockMarket.ViewComponents;


public class SelectedStockViewComponent : ViewComponent
{
    private readonly TradingOptions _tradingOptions;
    private readonly IStocksService _stocksService;
    private readonly IFinnhubService _finnhubService;
    private readonly IConfiguration _configuration;


    /// <summary>
    /// Constructor for TradeController that executes when a new object is created for the class
    /// </summary>
    /// <param name="tradingOptions">Injecting TradeOptions config through Options pattern</param>
    /// <param name="stocksService">Injecting StocksService</param>
    /// <param name="finnhubService">Injecting FinnhubService</param>
    /// <param name="configuration">Injecting IConfiguration</param>
    public SelectedStockViewComponent(IOptions<TradingOptions> tradingOptions, IStocksService stocksService, IFinnhubService finnhubService, IConfiguration configuration)
    {
        _tradingOptions = tradingOptions.Value;
        _stocksService = stocksService;
        _finnhubService = finnhubService;
        _configuration = configuration;
    }

    public async Task<IViewComponentResult> InvokeAsync(string? stockSymbol)
    {
        Dictionary<string, object>? companyProfileDict = null;

        if (stockSymbol != null)
        {
            companyProfileDict = await _finnhubService.GetCompanyProfile(stockSymbol);
            var stockPriceDict = await _finnhubService.GetStockPriceQuote(stockSymbol);
            if (stockPriceDict != null && companyProfileDict != null)
            {
                companyProfileDict.Add("price", stockPriceDict["c"]);
            }
        }

        if (companyProfileDict != null && companyProfileDict.ContainsKey("logo"))
            return View(companyProfileDict);
        else
            return Content("");
    }
}

StockMarket/StockMarket/Views/Stocks/Explore.cshtml
@model List<Stock>

@{
    ViewBag.Title = "Explore";
    ViewBag.CurrentUrl = "~/Explore";
}


<div class="flex">
    <div class="flex-1">
        <div class="text-grey ml">
            <span>Stocks</span>
            <i class="fa-solid fa-caret-right"></i>
            <span>Explore</span>
        </div>
    </div>

    <div class="flex-1 text-right">
    </div>
</div>

<div class="flex stocks-list">
    <div class="flex-1" id="stocks-list">
        <div class="box">

            <div class="flex">
                <div class="flex-1">
                    <h4 class="text-grey mb">Stocks</h4>
                </div>

                <div class="flex-1 text-right">
                    <a href="~/Stocks/Explore?showAll=true" class="mr">Show all stocks</a>
                </div>
            </div>


            <ul class="list">
                @foreach (Stock stock in Model)
                {
                    <li>
                        @if (Context.Request.Query.ContainsKey("showAll"))
                        {
                            <a href="~/Stocks/Explore/@stock.StockSymbol?showAll=@Context.Request.Query["showAll"]">
                                <h4>@stock.StockName</h4>
                                <div class="text-grey">(@stock.StockSymbol)</div>
                            </a>
                        }
                        else
                        {
                            <a href="~/Stocks/Explore/@stock.StockSymbol">
                                <h4>@stock.StockName</h4>
                                <div class="text-grey">(@stock.StockSymbol)</div>
                            </a>
                        }

                    </li>
                }
            </ul>

            @if (Model.Count == 0)
            {
                <div class="mt text-blue">No stocks</div>
            }
        </div>

    </div>

    <div class="flex-1" id="stock-details">
        @if (ViewBag.stock != null)
        {
            <vc:selected-stock stock-symbol="@ViewBag.stock"></vc:selected-stock>
        }
    </div>
</div>