StockMarket/StockMarket/Models/Orders.cs
using ServiceContracks.DTO;

namespace StockMarket.Models;

public class Orders
{
    public List<BuyOrderResponse> BuyOrders { get; set; } = new List<BuyOrderResponse>();
    public List<SellOrderResponse> SellOrders { get; set; } = new List<SellOrderResponse>();
}

StockMarket/StockMarket/Controllers/TradeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using Rotativa.AspNetCore;
using ServiceContracks;
using ServiceContracks.DTO;
using StockMarket.Filters;
using StockMarket.Models;
using System.Collections.Generic;

namespace StockMarket.Controllers
{
    public class TradeController : Controller
    {
        private readonly TradingOptions _tradingOptions;
        private readonly IFinnhubService _finnhubService;
        private readonly IStocksService _stocksService;
        private readonly IConfiguration _configuration;

        // Logger
        private readonly ILogger<TradeController> _logger;

        /// <summary>
        /// Constructor for TradeController that executes when a new object is created for the class
        /// </summary>
        /// <param name="tradingOptions">Injecting TradeOptions config through Options pattern</param>
        /// <param name="stocksService">Injecting StocksService</param>
        /// <param name="finnhubService">Injecting FinnhubService</param>
        /// <param name="configuration">Injecting IConfiguration</param>
        public TradeController(IOptions<TradingOptions> tradingOptions, IFinnhubService finnhubService,IStocksService stocksService ,IConfiguration configuration, ILogger<TradeController> logger)
        {
            _tradingOptions = tradingOptions.Value;
            _finnhubService = finnhubService;
            _stocksService = stocksService;
            _configuration = configuration;
            _logger = logger;
        }

        [Route("~/[controller]/[action]/{stockSymbol}")]
        [Route("~/[controller]/{stockSymbol}")]
        public async Task<IActionResult> Index(string stockSymbol)
        {
            // Logger
            _logger.LogInformation("In TradeController.Index() action method");
            _logger.LogDebug("strockSymbol: {stockSymbol}", stockSymbol);

            // reset Stock symbol if not exists
            if (string.IsNullOrEmpty(stockSymbol))
                stockSymbol = "MSFT";

            //get company profile from API server
            Dictionary<string, object>? companyProfileDictionary = await _finnhubService.GetCompanyProfile(stockSymbol);

            //get stock price quotes from API server
            Dictionary<string, object>? stockQuoteDictionary = await _finnhubService.GetStockPriceQuote(stockSymbol);

            //create model object
            StockTrade stockTrade = new StockTrade() { StockSymbol = stockSymbol };

            //load data from finnHubService into model object
            if (companyProfileDictionary != null && stockQuoteDictionary != null)
            {
                stockTrade = new StockTrade() { StockSymbol = Convert.ToString(companyProfileDictionary["ticker"]), StockName = Convert.ToString(companyProfileDictionary["name"]),Quantity = _tradingOptions.DefaultOrderQuantity ?? 0, Price = Convert.ToDouble(stockQuoteDictionary["c"].ToString()) };
            }

            //Send Finnhub token to view
            ViewBag.FinnhubToken = _configuration["FinnhubToken"];

            return View(stockTrade);
        }

        [Route("[action]")]
        [HttpPost]
        [TypeFilter(typeof(CreateOrderActionFilter))]
        public async Task<IActionResult> BuyOrder(BuyOrderRequest buyOrderRequest)
        {
            // Update date of model
            buyOrderRequest.DateAndTimeOfOrder = DateTime.Now;

            // re-validate the model object after updating the date
            ModelState.Clear();
            TryValidateModel(buyOrderRequest);

            if (!ModelState.IsValid)
            {
                ViewBag.Error = ModelState.Values.SelectMany(x => x.Errors).Select(y => y.ErrorMessage).ToList();
                StockTrade stockTrade = new StockTrade()
                {
                    StockName = buyOrderRequest.StockName,
                    Quantity = buyOrderRequest.Quantity,
                    StockSymbol = buyOrderRequest.StockSymbol,
                };

                return View("Index", stockTrade);
            }

            //invoke service method
            BuyOrderResponse buyOrderResponse = await _stocksService.CreateBuyOrder(buyOrderRequest);

            return RedirectToAction(nameof(Orders));
        }

        [Route("[action]")]
        [HttpPost]
        [TypeFilter(typeof(CreateOrderActionFilter))]
        public async Task<IActionResult> SellOrder(SellOrderRequest sellOrderRequest)
        {
            // Update date of model
            sellOrderRequest.DateAndTimeOfOrder = DateTime.Now;

            // re-validate the model object after updating the date
            ModelState.Clear();
            TryValidateModel(sellOrderRequest);

            if (!ModelState.IsValid)
            {
                ViewBag.Errors = ModelState.Values.SelectMany(v => v.Errors).Select(e => e.ErrorMessage).ToList();
                StockTrade stockTrade = new StockTrade() { StockName = sellOrderRequest.StockName, Quantity = sellOrderRequest.Quantity, StockSymbol = sellOrderRequest.StockSymbol };
                return View("Index", stockTrade);
            }

            //invoke service method
            SellOrderResponse sellOrderResponse = await _stocksService.CreateSellOrder(sellOrderRequest);

            return RedirectToAction(nameof(Orders));
        }

        [Route("[action]")]
        public async Task<IActionResult> Orders()
        {
            List<BuyOrderResponse> buyOrderResponses = await _stocksService.GetBuyOrders();
            List<SellOrderResponse> sellOrderResponses = await _stocksService.GetSellOrders();

            Orders orders = new Orders()
            {
                BuyOrders = buyOrderResponses,
                SellOrders = sellOrderResponses
            };

            ViewBag.TraddingOptions = _tradingOptions;

            return View(orders);
        }

        [Route("OrdersPDF")]
        public async Task<IActionResult> OrdersPDF()
        {
            //Get list of orders
            List<IOrderResponse> orders = new List<IOrderResponse>();
            orders.AddRange(await _stocksService.GetBuyOrders());
            orders.AddRange(await _stocksService.GetSellOrders());
            orders = orders.OrderByDescending(temp => temp.DateAndTimeOfOrder).ToList();

            ViewBag.TradingOptions = _tradingOptions;

            //Return view as pdf
            return new ViewAsPdf("OrdersPDF", orders, ViewData)
            {
                PageMargins = new Rotativa.AspNetCore.Options.Margins() { Top = 20, Right = 20, Bottom = 20, Left = 20 },
                PageOrientation = Rotativa.AspNetCore.Options.Orientation.Landscape
            };
        }
    }
}

StockMarket/StockMarket/Views/Trade/Index.cshtml
@model StockTrade

@{
    ViewBag.Title = "Trading";
    ViewBag.CurrentUrl = "~/Trade/Index";
}

<div class="text-grey ml">
    <span>Stocks</span>
    <i class="fa-solid fa-caret-right"></i>
    <span>@Model.StockName</span>
</div>

<form method="post">
    <div class="box trading-panel">

        <div class="flex trading-panel-flex">
            <div id="stock-price-panel">

                <div class="stock">
                    <h1 class="stock-title">@Model.StockName (@Model.StockSymbol)</h1> 
                    <h2 class="stock-price"><small class="text-grey">$</small> <span class="price">@Model.Price.ToString()</span></h2>
                </div>

                    <div class="chart mt">
                        <canvas id="stock-chart" width="400px" height="150px"></canvas>
                    </div>

                <div class="date"></div>
            </div>

            <div id="new-order-panel">
                <div class="flex flex-direction-vertical">
                    <h3 class="text-grey mb">New Order</h3>

                    <label asp-for="Quantity" class="mt">Quantity:</label>
                    <div class="w-50">
                        <input type="number" name="Quantity" asp-for="Quantity" min="1" max="100000" placeholder="Quantity" required="required" class="form-input mb" autofocus="autofocus" />
                    </div>
                </div>

                <div class="button-panel">
                    <button type="submit" formaction="~/SellOrder" class="button button-red-back trading-button sell-button">
                        <i class="fa-solid fa-arrow-down"></i>
                        <span>Sell</span>
                    </button>

                    <button type="submit" formaction="~/BuyOrder" class="button button-green-back trading-button buy-button">
                        <i class="fa-solid fa-arrow-up"></i>
                        <span>Buy</span>
                    </button>

                    @if (ViewBag.Error != null){
                        <div class="text-red mt">
                            <ul>
                                @foreach (string error in ViewBag.Errors)
                                {
                                    <li class="ml">@error</li>
                                }
                            </ul>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>


    <input type="hidden" asp-for="StockSymbol" />
    <input type="hidden" asp-for="StockName" />
    <input type="hidden" asp-for="Price" id="price" />
    <input type="hidden" id="FinnhubToken" value="@ViewBag.FinnhubToken" />
</form>


@section Scripts
{
    @* Chart.js library file *@
     <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.9.1/chart.min.js" integrity="sha512-ElRFoEQdI5Ht6kZvyzXhYG9NqjtkmlkfYk0wr6wHxU9JEHakS7UJZNeml5ALk+8IKlU6jDgMabC3vkumRokgJA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    @* import the ChartScript.js file to display price chart *@
     <script src="~/js/ChartScript.js">
     </script>

    @* import the FinnhubScript.js file to update the price *@
         <script src="~/js/FinnhubScript.js">
     </script>

}

StockMarket/StockMarket/Views/Trade/Orders.cshtml
@model Orders

@{
    ViewBag.Title = "Orders";
    ViewBag.CurrentUrl = "~/Trade/Orders";
}


<div class="flex">
    <div class="flex-1">
        <div class="text-grey ml">
            <span>Stocks</span>
            <i class="fa-solid fa-caret-right"></i>
            <span>Orders</span>
        </div>
    </div>

    <div class="flex-1 text-right">
        <a asp-controller="Trade" asp-action="OrdersPDF" class="mr">Download as PDF</a>
    </div>
</div>

<div class="flex orders-list">
    <div id="buy-orders-list">
        <div class="box">
            <h4 class="text-grey mb">Buy Orders</h4>

            @foreach (BuyOrderResponse buyOrder in Model.BuyOrders)
            {
                <div class="border-bottom p">
                    <h3>@buyOrder.StockName (@buyOrder.StockSymbol)</h3>
                    <h5 class="mb">@buyOrder.Quantity <span class="text-grey">shares at </span> $@buyOrder.Price.ToString("N")</h5>
                    <h5 class="mb"><span class="text-grey">Trade Amount: </span> $@buyOrder.TradeAmount.ToString("N")</h5>

                    <div class="text-grey">@buyOrder.DateAndTimeOfOrder.ToString("dd MMMM yyyy hh:mm:ss tt")</div>
                </div>
            }

            @if (Model.BuyOrders.Count == 0)
            {
                <div class="mt text-blue">No orders</div>
            }
        </div>

    </div>

    <div id="sell-orders-list">
        <div class="box">
            <h4 class="text-grey mb">Sell Orders</h4>

            @foreach (SellOrderResponse sellOrder in Model.SellOrders)
            {
                <div class="border-bottom p">
                    <h3>@sellOrder.StockName (@sellOrder.StockSymbol)</h3>
                    <h5 class="mb">@sellOrder.Quantity <span class="text-grey">shares at </span> $@sellOrder.Price.ToString("N")</h5>
                    <h5 class="mb"><span class="text-grey">Trade Amount: </span> $@sellOrder.TradeAmount.ToString("N")</h5>

                    <div class="text-grey">@sellOrder.DateAndTimeOfOrder.ToString("dd MMMM yyyy hh:mm:ss tt")</div>
                </div>
            }

            @if (Model.SellOrders.Count == 0)
            {
                <div class="mt text-blue">No orders</div>
            }
        </div>

    </div>
</div>

StockMarket/StockMarket/Views/Trade/OrdersPDF.cshtml
@model IEnumerable<IOrderResponse>

@{
    Layout = null;
}

<link href="@("http://" + Context.Request.Host.ToString() + "/Stylesheet.css")" rel="stylesheet" />
@* http://localhost:port/StyleSheet.css *@

<h1>Orders</h1>

<table class="table w-100 mt">
    <thead>
        <tr>
            <th>Date and Time</th>
            <th>Stock</th>
            <th>Order Type</th>
            <th>Quantity</th>
            <th>Price</th>
            <th>Trade Amount</th>
        </tr>
    </thead>
    <tbody>
        @foreach (IOrderResponse order in Model)
        {
            <tr>
                <td style="width:18%">@order.DateAndTimeOfOrder.ToString("dd MMMM yyyy hh:mm:ss tt")</td>
                <td style="width:20%">@order.StockName (@order.StockSymbol)</td>
                <td style="width:10%">@order.TypeOfOrder.ToString()</td>
                <td style="width:9%">@order.Quantity</td>
                <td style="width:9%">$ @order.Price.ToString("N")</td>
                <td style="width:13%">@order.TradeAmount.ToString("N")</td>
            </tr>
        }
    </tbody>

</table>